version: "3"
services:
  tcp_server:
    build: ./tcp-server
    ports:
      - 8081:8081
    networks:
      - test_network
  tcp_client:
    build: ./tcp-client
    networks:
      - test_network
networks:
  test_network: