// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// IServer is an autogenerated mock type for the IServer type
type IServer struct {
	mock.Mock
}

// CloseConn provides a mock function with given fields:
func (_m *IServer) CloseConn() {
	_m.Called()
}

// ReceiveMessage provides a mock function with given fields: ctx
func (_m *IServer) ReceiveMessage(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveMessage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunServer provides a mock function with given fields: ctx
func (_m *IServer) RunServer(ctx context.Context) (net.Listener, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunServer")
	}

	var r0 net.Listener
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (net.Listener, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) net.Listener); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Listener)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMessage provides a mock function with given fields: ctx, mess
func (_m *IServer) SendMessage(ctx context.Context, mess []byte) error {
	ret := _m.Called(ctx, mess)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, mess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetConn provides a mock function with given fields: conn
func (_m *IServer) SetConn(conn net.Conn) {
	_m.Called(conn)
}

// NewIServer creates a new instance of IServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IServer {
	mock := &IServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
