# Номер порта для соединения с tcp-сервером
port: 8081

# Имя сервиса для отображения в логах
serviceName: "tcp-client"

# Количество клиентов, которое будет запущено
clientsCount: 5

# Интервал в миллисекундах между запуском горутин с клиентами
connInterval: 10

# Уровень логирования
logLevel: "Debug"