# Адрес для соединения с tcp-сервером. Имя "tcp_server" должно совпадать с именем сервера в файле docker-compose.yml
address: "tcp_server:8081"

# Имя сервиса для отображения в логах
serviceName: "tcp-client"

# Количество клиентов, которое будет запущено
clientsCount: 5

# Интервал в миллисекундах между запуском горутин с клиентами
connInterval: 10

# Уровень логирования
logLevel: "Debug"