// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// ClientProvider is an autogenerated mock type for the ClientProvider type
type ClientProvider struct {
	mock.Mock
}

// CloseConn provides a mock function with given fields: conn
func (_m *ClientProvider) CloseConn(conn net.Conn) {
	_m.Called(conn)
}

// ReceiveMessage provides a mock function with given fields: ctx, conn
func (_m *ClientProvider) ReceiveMessage(ctx context.Context, conn net.Conn) (string, error) {
	ret := _m.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveMessage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, net.Conn) (string, error)); ok {
		return rf(ctx, conn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, net.Conn) string); ok {
		r0 = rf(ctx, conn)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, net.Conn) error); ok {
		r1 = rf(ctx, conn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Run provides a mock function with given fields: ctx
func (_m *ClientProvider) Run(ctx context.Context) (net.Conn, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (net.Conn, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) net.Conn); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMessage provides a mock function with given fields: ctx, conn, mess
func (_m *ClientProvider) SendMessage(ctx context.Context, conn net.Conn, mess []byte) error {
	ret := _m.Called(ctx, conn, mess)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, net.Conn, []byte) error); ok {
		r0 = rf(ctx, conn, mess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClientProvider creates a new instance of ClientProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientProvider {
	mock := &ClientProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
