# Номер порта для соединения с tcp-сервером
tcpPort: ":8081"

# Имя сервиса для отображения в логах
serviceName: "tcp-server"

# Условие сложности для Proof of work
difficulty: 10
proofString: "Find a string that, when hashed, can be proofed"

# Уровень логирования
logLevel: "Debug"